[global]
output_dir = 'run_default'
crs = 'EPSG:4326'

[hazard]
grid_file = '.\hazard\event_map.nc'
crs = 'EPSG:4326'
return_period = 'Event'
spatial_reference = 'DEM'

[exposure]
geom_file = '.\exposure\spatial.gpkg'
dbase_file = '.\exposure\spatial.csv'
crs = 'EPSG:4326'

[vulnerability]
dbase_file = '.\vulnerability\vulnerability_curves.csv'

[categorical_bins]
low = 0.25
medium-low = 0.5
medium-high = 0.75
high = 1