---
title: "Exposure data"
---

The **exposure data** describe the assets within the region of interest. FIAT allows **vector and raster data** inputs. It is recommended to place the exposure data in the 'exposure' folder, see the [FIAT folder structure page](folder_structure.qmd). However, the file name is free to be chosen by the user and must simply be refered to in the [settings.toml](settings.qmd) configuration file.

::: {.callout-tip}
You can also create your exposure data with the [**HydroMT-FIAT  model builder**](https://deltares.github.io/hydromt_fiat/latest/#)
:::


## Geometry data
FIAT can be used to assess flood damages to buildings, roads, utilities, and other types of structures of which data is available. These type of assets are often spatially represented with vector, or geometry data. Building a FIAT model with geometry exposure data requires two data types:

1. A or multiple **geometry files** (see acceptable file types at the bottom of this page) with an attribute `Object ID` that holds unique IDs over all geometry files
2. One **CSV file** containing a column `Object ID` linking to the geometries in the geometry file(s) and exposure information like maximum potential damages


### Geometry file
A user can specify one or multiple **geometry files** in the [settings.toml](settings.qmd). It is advisable to give descriptive names to the geometry files, e.g., *buildings.gpkg* or *roads.gpkg*. Most-used file types are GeoPackages or Shapefiles but more file types are accepted as can be seen at the bottom of this page. All geometry files must have an attribute `Object ID` that holds unique IDs over all geometry files, linking to the `Object ID` column in the exposure CSV file (see below).

::: {.callout-tip title="Example"}
When using a GeoPackage file with roads containing `Object IDs` 1-100, a second GeoPackage file with building footprints should contain `Object ID`s from 101-n. Then, those IDs should link to the corresponding rows and IDs in the exposure CSV file.
:::

When providing a polygon or line geometry file, a user can choose to use the *area extraction method* ('extraction method' = 'area', see @tbl-exposure) for considering water levels or depths over the whole area of the asset. This can be more appropriate than point estimates for example for large buildings.

::: {.callout-warning}
Assets cannot be partially or fully outside the hazard map extent! FIAT will stop if it detects any.
:::

### CSV
The exposure data CSV file contains information about each asset in the area of interest that is needed for the damage calculation. Each row represents one asset, such as a building, road segment, or utility, and each column represents an attribute of the asset, such as its location, elevation or maximum potential damage value.
For users that want to create their own exposure data, or modify existing exposure data, a description of the default fields (columns) in the exposure data CSV can be found in @tbl-exposure.

::: {.callout-tip title="Tip"}
Users can add as many columns to the exposure CSV as they want, for example, to later identify the most damaged administrative areas. All data field will also be saved in the output of FIAT.
:::


| Field                                  | Description                                                                                | Required                                 | Example                    |
|----------------------------------------|--------------------------------------------------------------------------------------------|------------------------------------------|----------------------------|
| Object ID                              | Unique numerical identifier of the object                                                 | Yes                                      | 1                          |
| Object Name                            | Unique name of the object                                                                  | No                                       | fp_1                       |
| Primary Object Type                    | General object type                                                                                | No                                       | RES1_1SNB                  |
| Secondary Object Type                  | More specific object type                                                       | No                                       | Res 1,1 Story no basement  |
| Extraction Method                      | Method to extract water depth                                                              | Yes                                      | options: 'centroid' or 'area' |
| Damage Function: Structure             | Damage function for the structure                                                          | at least one Damage Function of any kind | struct_2                   |
| Damage Function: Content               | Damage function for the content                                                            | at least one Damage Function of any kind | cont_62                    |
| Damage Function: RoadOutages                 | Damage function for road outages                                                         | at least one Damage Function of any kind |                            |
| Ground Floor Height                    | Elevation of the ground floor above the ground elevation. Units must be coherent with hazard map | Yes                                      | 4                          |
| Ground Elevation                       | Ground elevation relative to datum at location of the asset. Units must be coherent with hazard map             | Yes, if water level map as hazard input  | 10.11                      |
| Max Potential Damage: Structure        | Maximum potential structural damage (use the same name as the related damage function)                                                        | a Max Potential Damage per damage function        | 193457.00                  |
| Max Potential Damage: Content          | Maximum potential content damage (use the same name as the related damage function)                                                           | a Max Potential Damage per damage function        | 386984.00                  |
| Max Potential Damage: RoadOutages            | Maximum potential other damage (e.g. road outages) (use the same name as the related damage function)                                                | a Max Potential Damage per damage function        |                            |
| <e.g., Census Tract> | For example, another column to later aggregate damages by, in this case, Census Tract                                                         | No                                       | 1205                       |
: exposure.csv input {#tbl-exposure .striped .hover .column-page-inset-right}

A more detailed description of the data fields in the *exposure.csv* can be found below.

**Object ID**
The object ID is used to link the geometries to the information in the exposure CSV. The object ID must be unique for each object. At the moment of writing, FIAT does not check whether the object IDs are indeed unique and it is the responsibility of the user to ensure this. At a later stage, FIAT will have a built-in check for this.
 
**Object name**
The object name field can be chosen freely and can serve as a field for identifying the damages assets.

**Primary/Secondary object type**
The primary object type describes the occupancy or category of the asset (e.g. residential or commercial). The secondary object type allows for a more detailed profile of the object (e.g. single-story home or grocery store). The developer of the exposure dataset is free to set their own categories of asset types.

::: {.callout-tip title="Tip"}
Defining primary/secondary object types can facilitate the assignment of damage functions to the assets for the user by creating automatic look-up tables.
:::

**Extraction Method**
The extraction method refers to how the water level or water depth is sampled per asset. The options are (1) *centroid*, which samples the water level or depth at the estimated centroid inside of the asset, or (2) area, which considers the water level or depth over the entire polygon or line and takes either an average or maximum. The user can set the choice for the latter per damage function, in the [vulnerability curves file](vulnerability.qmd).

::: {.callout-important}
 In case the user selects 'area' as extraction method for certain assets, the geometries related to those assets should be a line or polygon.
:::

**Damage Functions**
The user can input as many damage functions and related max potential damages as required. However, at least one damage function and related max potential damage must be provides per asset. Damage function column are named as **"Damage Function: `damage function name`"**. This name can be chosen freely but it is recommended to give it a descriptive name, such as *structure* or *content*, and it is required to use the same name in the max potential damage column. The value that must be entered is the name of the damage function, relating to the names in the corresponding damage functions in the [vulnerability curves file](vulnerability.qmd). Globally, continental damage functions can be obtained from [European Commission's Joint Research Centre](https://publications.jrc.ec.europa.eu/repository/handle/JRC105688), but it is recommended to use more location-specific functions when available.

**Ground Floor Height**
The ground floor height column indicates the height of the ground floor of an asset above the ground elevation. For example, when a building is built on poles, the ground floor (finished floor in the US) is lifted off the ground with a certain height. Usually, buildings are at least a certain amount above ground elevation because of the road and sidewalk. This value is used to calculate the water depth inside of the asset, for buildings.

**Ground Elevation**
The ground elevation is the value of a digital elevation model (DEM) at the location of the asset.

**Max Potential Damage**
The maximum potential damage corresponds to the damage functions for each asset. For each damage function type that was assigned, a maximum potential damage must also be assigned. These values represent the maximum damage to, for example, the structure, content, or other (e.g. inventory). There are methods to derive these values, based on building type and area of the building. Globally, maximum damage values per country can be obtained from [European Commission's Joint Research Centre](https://publications.jrc.ec.europa.eu/repository/handle/JRC105688), but it is recommended to use more location-specific damage values. In the US, [FEMA Hazus](https://www.fema.gov/flood-maps/products-tools/hazusis) is an industry standard in how to derive these values.

**Additional attributes**
Attitional attributes can be added to the exposure CSV file. The added columns can be named freely. The resulting FIAT output contains all data that was put in, therefore they can be used by the [**FIAT Toolbox**](https://github.com/Deltares/fiat_toolbox) to calculate user-specified output metrics. For example, a user could configure the output metrics to always show the number of people affected with a high social vulnerability, per administrative region. The user can add columns to the CSV file manually or with the help of the [**HydroMT-FIAT model builder**](https://deltares.github.io/hydromt_fiat/latest/#), in which the user is free to select a descriptive *'Label name'* for the additional attributes. If the user wishes to connect the damages per administrative or other aggregation area to a GIS file, the [**FIAT Toolbox**](https://github.com/Deltares/fiat_toolbox) offers a post-processing tool to do so.


###### <ins><h14>*exposure geometry file types*</h14></ins>
    {acceptable exposure file types:'.fits': 'FITS', '.pix': 'PCIDSK', '.nc': 'netCDF', '.xml': 'PDS4', '.pdf': 'PDF', '.mbtiles': 'MBTiles', '.bag': 'BAG', '.shp': 'ESRI Shapefile', '.mid': 'MapInfo File', '.000': 'S57', '.dgn': 'DGN', '.csv': 'CSV', '.gml': 'GML', '.gpx': 'GPX', '.kmz': 'LIBKML', '.kml': 'KML', '.geojson': 'GeoJSON', '.geojsons': 'GeoJSONSeq', '.gmt': 'OGR_GMT', '.gpkg': 'GPKG', '.sqlite': 'SQLite', '.map': 'WAsP', '.gdb': 'OpenFileGDB', '.dxf': 'DXF', '.dwg': 'CAD', '.fgb': 'FlatGeobuf', '.txt': 'Geoconcept', '.sql': 'PGDUMP', '.igc': 'GPSBabel', '.ods': 'ODS', '.xlsx': 'XLSX', '.jml': 'JML', '.x10': 'VDV', '.mvt': 'MVT', '': 'Memory'}


## Raster Data

::: {.callout-important}
 This functionality is in beta phase
:::

Raster files must be **pre-processed** before being ingested into the FIAT model. Raster projection and extent must be coherent among exposure rasters and hazard maps. For each object type (e.g. residential buildings, industrial assets) a raster file with the **max potential damage** per cell is required. A damage function must be assigned to each raster file as well, linking with the damage function name in the meta data to the name in the [vulnerability curves file](vulnerability.qmd).
