---
title: "Settings file"
---
The model settings are configured in a *settings.toml* file. The configuration file consists of important core information and can be extended with a range of optional input, see @tbl-toml. More advanced options are described in the [Advanced options](../advanced.qmd) page.

For a simple model the configuration file only needs the required fields and can be kept rather simple:

```html
[output]
path = "output" 

[output.csv]
name = "output.csv" 

[output.geom]
name1 = "spatial.gpkg"

[hazard]
file = "hazard/SL_10yr_reprojected.tif"
crs = "EPSG:4326"
elevation_reference = "DEM"
risk = false

[exposure.geom]
csv = "./exposure/exposure.csv"
crs = "EPSG:4326"
file1 = "./exposure/buildings.gpkg"

[vulnerability]
file = "./vulnerability/vulnerability_curves.csv"

```

[**output**]  
`path` :  This will create an output folder in the working directory 

[**output.csv**]  
`name`: This will create an output CSV file that contains the information from the exposure.csv and the damages per asset

[**output.geom**]  
`name1`: This will create an output vector file that contains the objects and the    
damages per asset

[**hazard**]  
`file`: The file path to the hazard file  
`crs`: The projection of the hazard file. If no global projection is defined, the output will be in the same projection as the hazard map.   
`elevation_reference`: In this case the hazard input is a flood map, therefore "DEM" is defined as reference. If it would be an elevation map the input would be "datum"  
`risk`: in this case "false" as a single event is assessed. 

[**exposure.geom**]
`csv`: This will create an exposure CSV file within the exposure folder ([folder strucute](folder_structure.qmd)) that contains the [required information](exposure.qmd) per asset.  
`crs`: The projection of the exposure vector file.  
`file1`: This will create an exposure vector file within the exposure folder with the assets'geometry and Object ID.

[**vulnerability**]  
`file`: This will create an vulnerability curves CSV file within the vulnerability folder ([folder strucute](folder_structure.qmd)) that contains the damage curves. 

::: {.callout-note}
File paths in the settings can be relative to the settings.toml file or absolute.
:::

If the user prefers to create a more advanced model or to utilize grid data instead of object data, FIAT offers the flexibility to customize settings for each variable (@tbl-toml)

| Field                        | Description                                                                                                                                                                  | Required                            | Default                                                                   | Example                                   |
|------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------|---------------------------------------------------------------------------|-------------------------------------------|
| **[global]**                 |                                                                                                                                                                              |                                     |                                                                           |                                           |
| crs                          | Global projection for the model and the output. If not defined, the default crs for the model output is the same as the hazard map.                                          | No                                  | hazard map projection                                                     | 'EPSG:32617'                              |
| **[global grid]**            |                                                                                                                                                                              |                                     |                                                                           |                                           |
| chunk                        | Divide grid into smaller chunks. Define grid chunk size                                                                                                                      | No                                  |                                                                           | [1024, 1014]                              |
| **[output]**                 |                                                                                                                                                                              |                                     |                                                                           |                                           |
| path                         | Set directory path to save the output                                                                                                                                        | Yes                                 |                                                                           | 'output'                                  |
| **[output.csv]**             |                                                                                                                                                                              |                                     |                                                                           |                                           |
| name                         | File name of the output.csv file containing the exposure data incl. the damage per asset.                                                                                    | Yes                                 | 'output.csv'                                                              | 'output.csv'                              |
| **[output.geom]**            |                                                                                                                                                                              |                                     |                                                                           |                                           |
| name1                        | File name of the output vector data. Can be various spatial files. Find details about  file formats in the data documentation.                                               | Yes                                 |                                                                           | 'spatial.gpkg'                            |
| **[output.grid]**            |                                                                                                                                                                              | optional                            |                                                                           |                                           |
| name                         | File name of the output for the grid model; WARN: not fully implemented yet                                                                                                  | Yes, if working with grid           | 'output.nc'                                                               | 'output.nc'                               |
| **[hazard]**                 |                                                                                                                                                                              |                                     |                                                                           |                                           |
| file                         | Directory path to hazard file (raster or netCDF). Can contain one (for events) or multiple (for return periods) bands                                                        | Yes                                 |                                                                           | 'hazard/event_map.nc'                     |
| crs                          | Projection of hazard data                                                                                                                                                    | Yes, if crs is unknown in dataset   |                                                                           | 'EPSG:32617'                              |
| elevation_reference          | Define the elevation reference. Either Digital Elevation Model (Flood depth map) or Datum (Flood elevation map)                                                              | Yes                                 |                                                                           | 'dem'                                     |
| risk                         | Hazard input is a returning event and multiple flood maps are ingested to compute the risk. True/False If true, risk (EAD) is computed. If false, a single event is computed | Yes                                 |                                                                           | True                                      |
| return_periods               | Return periods for hazard calculation when they cannot be inferred from the data itself                                                                                      | No                                  |                                                                           | [2, 5, 10, 25]                            |
| **[hazard.settings]**        |                                                                                                                                                                              |                                     |                                                                           |                                           |
| subset                       | Specific layer from a multilayered netCDF file (GDAL can't read those properly)                                                                                              | No                                  |                                                                           | 'zs'                                      |
| var_as_band                  | True/False Read netCDF subdatasets as raster bands                                                                                                                           | No                                  |                                                                           | False                                     |
| **[exposure.geom]**          |                                                                                                                                                                              |                                     |                                                                           |                                           |
| csv                          | File path to exposure.csv file, that contains information about e.g. asset type, max. potential damage, aggregation and so forth)                                            | Yes                                 | 'exposure/exposure.csv'                                                   | 'exposure/exposure.csv'                   |
| file1                        | File path of exposure vector file with Object ID column to enable linking exposure.csv output to vector file.                                                                | Yes                                 | **buildings**: 'exposure/buildings.gpkg' **roads**: 'exposure/roads.gpkg' | 'exposure/buildings.gpkg'                 |
| crs                          | Projection of exposure data                                                                                                                                                  | Yes, if crs is unknown in dataset   |                                                                           | 'EPSG:32617'                              |
| index                        | Define the name of the index column of the data to link the exposure CSV file with the exposure vector file.                                                                 | No                                 | 'Object ID'                                                               | 'Object ID'                               |
| **[exposure.grid]**          |                                                                                                                                                                              |                                     |                                                                           |                                           |
| file                         | File path to exposure.nc grid file, that contains the spatial information and information about the maximum potential damage per cell.                                       | Yes, if netCDF is provided as input | 'exposure/raster.nc'                                                      | 'exposure/raster.nc'                      |
| crs                          | Output projection                                                                                                                                                            | Yes, if crs is unknown in dataset   |                                                                           | 'EPSG:32617'                              |
| **[exposure.grid.settings]** |                                                                                                                                                                              |                                     |                                                                           |                                           |
| var_as_band                  | True/False Read netCDF subdatasets as raster bands                                                                                                                           | No                                  |                                                                           | True                                      |
| **[vulnerability]**          |                                                                                                                                                                              |                                     |                                                                           |                                           |
| file                         | File path to vulnerability_curves.csv file, that contains the damage functions.                                                                                              | Yes                                 |                                                                           | 'vulnerability/ vulnerability_curves.csv' |
: Settings.toml input (required and optional fields) {#tbl-toml .striped .hover .column-page-inset-right}
