---
title: Supported formats
---

## Settings file
For the settings file, only one format is supported:

- [toml](https://toml.io/en/)

## Comma seperated values (CSV)
Your run of the mill csv files.
As long as one provides the delimiter in the settings file, anything goes.
For example:

- comma
- semicolon
- tab

The amount of columns are determined by length of the header or the first line of data.

## Geometry files
For geometry files only one file format is supported:

- [FlatGeobuf]

Only files containing a spatial index (hilbert r-tree) are allowed.
This allowes fiat to quickly index features and batches of features.

## Gridded data files
Two formats are supported by fiat when it comes to raster (gridded) files.

- [GeoTIFF](https://www.ogc.org/standards/geotiff/)
- [NetCDF](https://www.unidata.ucar.edu/software/netcdf/)

GeoTIFF files are accepted in plain form and in it's cloud optimized form.
NetCDF files need to comply with the GDAL standard for this format. This entails
the presense of specific metadata
