[project]
name = "delft_fiat"
version = "0.1.0"
description = "Add a short description here"
authors = ["B.W. Dalmijn <brencodeert@outlook.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[tasks]

install = { depends_on = ["install-fiat", "install-pre-commit"] }
install-fiat = "pip install --no-deps --editable ."
install-pre-commit = "pre-commit install"

lint = { cmd = ["pre-commit", "run", "--all"] }

docker-clean = { cmd = ["docker", "system", "prune", "-f"] }

generate-api = { cmd = ["python", "docs/api.py", "docs/_quarto.yml"] }
interlink-docs = { cmd = ["python", "docs/inv.py", "docs/_quarto.yml"] }
quarto-render = { cmd = ["quarto", "render", "docs", "--execute"] }
docs = { depends_on = [] }
docs-slim = { depends-on = ["interlinks-docs", "quarto-render"] }
serve = { cmd = ["python", "-m", "http.server", "8000", "-d", "docs/_site"] }

# clean
clean = { depends_on = [
  "clean-env-files",
  "clean-dist",
  "clean-docs-generated",
  "clean-docs-build",
  "clean-docs-exmaples",
] }
clean-env-files = { cmd = ["rm", "-f", "*environment.yml"] }
clean-dist = { cmd = ["rm", "-rf", "dist"] }
clean-docs-generated = { cmd = ["rm", "-rf", "docs/_generated"] }
clean-docs-build = { cmd = ["rm", "-rf", "docs/_build"] }
clean-docs-exmaples = { cmd = ["rm", "-rf", "docs/examples"] }

test = { cmd = ["pytest"] }
test-lf = { cmd = ["pytest", "--lf", "--tb=short"] }
test-cov = { cmd = [
  "pytest",
  "--verbose",
  "--cov=fiat",
  "--cov-report",
  "xml",
] }
test-cov-local = { cmd = [
  "pytest",
  "--verbose",
  "--cov",
  "--cov-report",
  "html",
] }

[dependencies]
gdal = ">=3.5"
numpy = "*"
regex = "*"
tomli = "*"
pip = ">=24.0,<25"

[feature.py310.dependencies]
python = "3.10.*"

[feature.py311.dependencies]
python = "3.11.*"

[feature.py312.dependencies]
python = "3.12.*"

[feature.all.dependencies]
setuptools = ">=61.0.0"

[feature.build.dependencies]
pyinstaller = ">=6.0.0"

[feature.dev.dependencies]
cython = "*"
pre-commit = "*"
ruff = "*"

[feature.docs.dependencies]
jupyter = "*"
jupyter-cache = "*"
matplotlib = "*"
pandas = "*"
quarto = "1.3.450"
quartodoc = "*"

[feature.extra.dependencies]
tomli-w = "*"

[feature.test.dependencies]
pytest = ">=2.7.3"
pytest-cov = "*"
pytest-dependency = "*"
pytest-mock = "*"
responses = "*"

[environments]
build = { features = ["py312", "all", "build"], solve-group = "py312"}
dev = { features = ["py312", "all", "dev", "docs", "extra", "test"], solve-group = "py312" }
fiat = { features = ["py312"], solve-group = "py312"}
min = { features = ["py312"], solve-group = "py312"}
test-py312 = {features = ["py312", "all", "extra", "test"], solve-group = "py312"}
test-py311 = {features = ["py311", "all", "extra", "test"], solve-group = "py311"}
test-py310 = {features = ["py310", "all", "extra", "test"], solve-group = "py310"}
