name: Feature Request
description: Propose an improvement for Delft-FIAT
title: "Improvement: "
labels: [enhancement]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Feature Type
      description: Please check what type of feature request you would like to propose.
      options:
        - label: >
            Adding new functionality
        - label: >
            Improving existing code
        - label: >
            Removing deprecated code/ clutter
  - type: textarea
    id: description
    attributes:
      label: Improvement Description
      description: >
        Please provide a clear and concise description of what your proposed improvement is:
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Implementation Description
      description: >
        Please describe how this would be implemented:
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: >
        Please add any other context about the improvement here:
