---
title: Computational input
---

The inputs give the user a bit more control over the computational aspects of FIAT.

| Entry                            | Type    | Default     |
|:---------------------------------|---------|-------------|
| **[model]**                      |         |             |
| [threads](#model)                | integer | 1           |
| **[model.geom]**                 |         |             |
| [chunk](#model.geom)             | integer | -           |
| **[model.grid]**                 |         |             |
| [chunk](#model.grid)             | list    | -           |
: Computational FIAT input settings {#tbl-toml .hover}

::: {.callout-warning}
All settings that are not globally defined (e.g. settings chunk size via `hazard.settings`) are ill-advised. Please use the global chunking settings.
:::

#### [model]

- `threads`: Set the number of threads of the calculations. If this number exceeds the cpu count, the amount of threads will be capped by the cpu count.

#### [model.geom]

- `chunk`: Set the chunk size of the geometry calculations. The calculations will then be done in vectors of these lengths in parallel. This settings will also be used for chunking when writing.

::: {.callout-tip}
This input benefits from multiple threads.
:::

::: {.callout-note}
This input is only applicable to the [GeomModel](../../info/models.qmd#geommodel)
:::

#### [model.grid]

- `chunk`: Set the chunk size for the gridded calculations. This will chunk the data in rectangles with the goal of reducing the memory foodprint. An example would be `[1024, 1024,]`.

::: {.callout-note}
This input is only applicable to the [GridModel](../../info/models.qmd#gridmodel)
:::
