[global]
crs = "EPSG:4326"
keep_temp_files = true

[output]
path = "output/risk_2g"

[output.csv]
name = "output.csv"

[output.geom]
name1 = "spatial.gpkg"
name2 = "spatial2.gpkg"

[hazard]
file = "hazard/risk_map.nc"
crs = "EPSG:4326"
elevation_reference = "DEM"
risk = true
return_periods = [
    2,
    5,
    10,
    25,
]

[hazard.multiband]
subset = ""
var_as_band = true

[exposure.grid]
file = "exposure/spatial.nc"
crs = "EPSG:4326"

[exposure.geom]
file1 = "exposure/spatial.gpkg"
csv = "exposure/spatial.csv"
crs = "EPSG:4326"
file2 = "exposure/spatial2.gpkg"

[vulnerability]
file = "vulnerability/vulnerability_curves.csv"
step_size = 0.01

[categorical_bins]
low = 0.25
medium-low = 0.5
medium-high = 0.75
high = 1
