project:
  type: website
  output-dir: "_site"
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!PDF_Documentation.qmd"
  post-render:
    - "examples/clear_notebooks.py"

filters:
   - include-code-files
   - interlinks
  #  - section-bibliographies

interlinks:
  sources:
    python:
      url: https://docs.python.org/3/
    numpy:
      url: https://numpy.org/doc/stable/

metadata-files:
  - api/_sidebar.yml

number-sections: false

website:
  title: "Delft FIAT"
  favicon: _static/logo.png
  search:
    location: navbar
    limit: 5
    type: textbox
  back-to-top-navigation: true
  page-footer:
    left: |
      Made possible by:
        <a href="https://www.deltares.nl/en" target="_blank" rel="noreferrer noopener">
          <img
            src="/_static/images/deltares-blue.svg"
            alt="Deltares"
            style="height: 40px;"
          />
        </a>
  navbar:
    logo: _static/logo.png
    search: true
    pinned: true
    left:
      - text: Getting Started
        file: getting_started/index.qmd
      - setup_guide/index.qmd
      - user_guide/index.qmd
      - api/index.qmd
      - text: "Developments"
        file: developments/index.qmd
    right:
      # - icon: _static/images/deltares-blue.svg
      #   href: https://www.deltares.nl/en
      #   aria-label: Deltares-Image
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/Deltares/Delft-FIAT
          - text: Report an Issue
            url:  https://github.com/Deltares/Delft-FIAT/issues/new/choose

  sidebar:
    - title: "Getting started"
      border: true
      collapse-level: 3
      contents:
        - text: Getting started
          file: getting_started/index.qmd
        - getting_started/faq.qmd
    - title: "Setup guide"
      collapse-level: 3
      contents:
        - setup_guide/index.qmd
        - section: "General setup"
          contents:
            - "setup_guide/general/conda.qmd"
        - section: "FIAT package"
          contents:
            - setup_guide/kernel/installation.qmd
            - setup_guide/kernel/application.qmd
            - setup_guide/kernel/linux.qmd
    - title: "User guide"
      collapse-level: 2
      contents:
        - user_guide/index.qmd
        - user_guide/data/settings.qmd
        - text: "Data"
          file: user_guide/data/data.qmd
          contents:
            - text: Hazard data
              file: user_guide/data/hazard.qmd
              contents:
                - user_guide/data/hazard_maps.qmd
            - text: Exposure data
              file: user_guide/data/exposure.qmd
              contents:
                - user_guide/data/exposure/csv.qmd
                - user_guide/data/exposure/geometries.qmd
            - user_guide/data/vulnerability.qmd
            - user_guide/data/supported.qmd
        - user_guide/models.qmd
        - examples/index.qmd
        - user_guide/advanced.qmd
    - title: "Developments"
      collapse-level: 3
      contents:
        - developments/index.qmd
        - changelog.qmd
        - developments/guide.qmd

format:
  html:
    theme:
      light: [cosmo, _static/theme-light.scss]
      dark: [cosmo, _static/theme-dark.scss]
    css: _static/styles.css
    toc: true
    toc-expand: false
    page-layout: article
    grid:
      content-mode: standard

# bibliography: references.bib
# citeproc: false

execute:
  freeze: auto
  cache: true

quartodoc:
  parser: numpy
  package: fiat
  title: API Reference
  style: pkgdown
  dir: api
  render_interlinks: true
  sidebar: api/_sidebar.yml
  options:
    include_imports: true
    include_inherited: true

  # Basics of FIAT
  sections:
    - title: Basics
    - subtitle: Core
      desc: Two main components of working with FIAT.
      package: fiat
      contents:
        - name: FIAT
          children: separate
        - name: ConfigReader
          children: separate
    - subtitle: Models
      desc: The individual models of FIAT.
      package: fiat.models
      contents:
        - name: GeomModel
          children: separate
        - name: GridModel
          children: separate

    # Logging
    - title: Logging
      desc: Logging module of FIAT
      package: fiat.log
      contents:
        - spawn_logger
        - setup_default_log
        - setup_mp_log
        - name: Log
          children: separate
        - Receiver

    # Geospatial methods
    - title: GIS
    - subtitle: Geometry (vector)
      desc: Geometry specific methods
      package: fiat.gis.geom
      contents:
        - point_in_geom
        - reproject
    - subtitle: Grid (raster)
      desc: Grid specific methods
      package: fiat.gis.grid
      contents:
        - reproject
    - subtitle: Overlay
      desc: For combined vector and raster methods
      package: fiat.gis.overlay
      contents:
        - clip
        - clip_weighted
        - pin
    - subtitle: Utility
      desc: Some utility for the GIS module (basic)
      package: fiat.gis.util
      contents:
        - world2pixel
        - pixel2world

    # I/O module
    - title: I/O
    - subtitle: Methods
      desc: Input/ output bound operations
      package: fiat.io
      contents:
        - open_csv
        - open_geom
        - open_grid
    - subtitle: Objects
      desc: Objects constructed from data
      package: fiat.io
      contents:
        - name: GeomSource
          children: separate
        - name: GridSource
          children: separate
        - name: Grid
          children: separate
        - name: Table
          children: separate
        - name: TableLazy
          children: separate
