project:
  type: website
  output-dir: "_site"
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!PDF_Documentation.qmd"

website:
  title: "Delft FIAT"
  favicon: _static/logo.png
  search:
    location: navbar
    limit: 5
    type: textbox
  navbar:
    logo: _static/logo.png
    search: true
    pinned: true
    left:
      - getting_started/index.qmd
      - setup_guide/index.qmd
      - user_guide/index.qmd
      - api/index.qmd
      - developments/index.qmd
    right:
      # - href: https://www.deltares.nl/en
      #   icon: _static/images/deltares-blue.svg
      #   aria-label: Deltares_org
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/Deltares/Delft-FIAT
          - text: Report an Issue
            url:  https://github.com/Deltares/Delft-FIAT/issues/new/choose

  sidebar:
    - title: "Getting started"
      border: true
      collapse-level: 3
      contents:
        - getting_started/index.qmd
        - getting_started/faq.qmd
    - title: "Setup guide"
      collapse-level: 3
      contents:
        - setup_guide/index.qmd
        - section: "General setup"
          contents:
            - "setup_guide/general/conda.qmd"
        - section: "FIAT package"
          contents:
            - setup_guide/kernel/installation.qmd
            - setup_guide/kernel/application.qmd
            - setup_guide/kernel/linux.qmd
    - title: "User guide"
      collapse-level: 3
      contents:
        - user_guide/index.qmd
        - user_guide/data/settings.qmd
        - section: "Data"
          contents:
            - user_guide/data/folder_structure.qmd
            - user_guide/data/hazard.qmd
            - user_guide/data/exposure.qmd
            - user_guide/data/vulnerability.qmd
        - section: "Examples"
          contents:
            - user_guide/examples.qmd
        - user_guide/advanced.qmd
    - title: "Developments"
      collapse-level: 3
      contents:
        - developments/index.qmd
        - developments/changelog.qmd
        - developments/roadmap.qmd
        - developments/guide.qmd

format:
  html:
    theme:
      light: [cosmo, _static/theme-light.scss]
      dark: [cosmo, _static/theme-dark.scss]
    css: _static/styles.css
    toc: true

# bibliography: references.bib
# citeproc: false

number-sections: false

filters:
   - include-code-files
  #  - section-bibliographies

execute:
  freeze: auto
  cache: true

metadata-files:
  - api/_sidebar.yml

quartodoc:
  parser: numpy
  package: fiat
  title: API Reference
  style: pkgdown
  dir: api
  sidebar: api/_sidebar.yml
  options:
    include_imports: true
    include_inherited: true

  # Basics of FIAT
  sections:
    - title: Basics
      desc: The higher level components of FIAT.
    - subtitle: Core
      desc: Two main components of working with FIAT.
      package: fiat.main
      contents:
        - name: FIAT
          children: separate
        - name: ConfigReader
          children: separate
    - subtitle: Models
      desc: The individual models of FIAT.
      package: fiat.models
      contents:
        - name: GeomModel
          children: separate
        - name: GridModel
          children: separate

    # Geospatial methods
    - title: GIS
      desc: Geospatial bound operations.
    - subtitle: Geometry (vector)
      desc: Geometry specific methods
      package: fiat.gis.geom
      contents:
        - point_in_geom
        - reproject
    - subtitle: Grid (raster)
      desc: Grid specific methods
      package: fiat.gis.grid
      contents:
        - reproject
    - subtitle: Overlay
      desc: For combined vector and raster methods
      package: fiat.gis.overlay
      contents:
        - clip
        - clip_weighted
        - pin
    - subtitle: Utility
      desc: Some utility for the GIS module (basic)
      package: fiat.gis.util
      contents:
        - world2pixel
        - pixel2world

    - title: I/O
      desc: Input/ output bound operations.
      package: fiat.io
      contents:
        - name: GeomSource
          children: separate
        - name: GridSource
          children: separate
        - name: Grid
          children: separate
      options:
        include_imports: true
        include_inherited: true
