---
name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test:
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest" ] #, "macos-latest", "windows-latest"]
        python-version: ["3.11"] # fix tests to support older versions
        include:
          - os: ubuntu-latest
            label: linux-64
            prefix: /usr/share/miniconda3/envs/fiat_test

    name: ${{ matrix.label }} - py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out source
        uses: actions/checkout@v3

      - name: Setup GDAL
        run: |
          chmod +x .build/setup_gdal.sh
          .build/setup_gdal.sh

      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniforge-variant: Miniforge3
          miniforge-version: latest
          use-mamba: true

      - name: Install environment with GDAL and FIAT
        run: |
          chmod +x .build/linux64_build_env.sh
          .build/linux64_build_env.sh

      - name: Build FIAT
        run: |
          chmod +x .build/linux64.sh
          .build/linux64.sh

      - name: Create Testdata
        run: |
          conda activate fiat_build
          pip install tomli-w
          python .testdata/create_test_data.py
          conda deactivate

      - name: Test Binary
        run: ./bin/Release/fiat run .testdata/settings.toml
