---
name: Build

on:
  push:
    branches: [ master ]
    paths:
      - .build/*
      - src/fiat/*
      - pyproject.toml
      - .github/workflows/build.yml
  pull_request:
    branches: [ master ]
    paths:
      - .build/*
      - src/fiat/*
      - pyproject.toml
      - .github/workflows/build.yml

jobs:
  Test:
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        include:
          - os: ubuntu-latest
            label: linux-64

    name: ${{ matrix.os }} - build
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pixi env
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: "v0.40.3"
          environments: linux-build
          locked: false
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'master' }}

      - name: Install fiat
        run: |
          pixi run -e linux-build install-fiat

      - name: Build FIAT
        run: |
          chmod +x .build/linux64.sh
          .build/linux64.sh

      - name: Create Testdata
        run: |
          pixi run -e build-linux generate-data

      - name: Test Binary
        run: ./bin/Release/fiat run .testdata/geom_event.toml
