---
name: Build Binary

on:
  push:
    branches: [ master ]
    paths:
      - .build/*
      - src/fiat/*
      - pyproject.toml
      - .github/workflows/build.yml
  pull_request:
    branches: [ master ]
    paths:
      - .build/*
      - src/fiat/*
      - pyproject.toml
      - .github/workflows/build.yml

jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        include:
          - os: ubuntu-latest
            label: linux-64

    name: ${{ matrix.os }} - build
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pixi env
        uses: prefix-dev/setup-pixi@v0.8.13
        with:
          pixi-version: "v0.49.0"
          environments: build-linux
          locked: false
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'master' }}

      - name: Build FIAT
        run: |
          pixi run -e build-linux build

      - name: Create Testdata
        run: |
          pixi run -e build-linux generate-data

      - name: Test Binary
        run: ./bin/Release/fiat run .testdata/geom_event.toml
