---
name: Build Image
on:
  push:
    branches:
      - master
    paths:
      - Containerfile
      - pyproject.toml
      - pixi.lock
      - .github/workflows/ci_docker.yml
  pull_request:
    branches:
      - master
    paths:
      - Containerfile
      - pyproject.toml
      - pixi.lock
      - .github/workflows/ci_docker.yml

jobs:
  image:
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
        include:
          - os: ubuntu-latest
            label: linux-64

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build image
        run: |
          podman build -f Containerfile \
          --build-arg="PIXIENV=default" --build-arg="UID=$(id -u)" \
          -t fiat .

      - name: Execute container
        run: |
          podman run --rm -v "${{ github.workspace }}/data:/home/deltares/data:U" \
          --entrypoint bash fiat:latest -lc \
          'pixi run testdata && pixi run fiat run data/geom_event.toml'
