---
name: Publish to PyPI

on:
  release:
    types:
      - published
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build-distributions:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.11'

      - name: generate env
        run: |
          pip install build tomli twine wheel

      - name: Build artifacts
        run: |
          python -m build --sdist
          python -m build --wheel
          python -m twine check dist/*

      - uses: actions/upload-artifact@v3
        with:
          name: releases
          path: dist

  test-built-dist:
    needs: build-distributions

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest" ] #, "macos-latest", "windows-latest"]
        python-version: ["3.11"] # fix tests to support older versions
        include:
          - os: ubuntu-latest
            label: linux-64
            prefix: /usr/share/miniconda3/envs/fiat_min
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: releases
          path: dist

      - name: List contents of built dist
        run: |
          ls -ltrh
          ls -ltrh dist

      - name: Generate env yaml
        run: pip install tomli && python make_env.py min -p ${{ matrix.python-version }}.*

      - name: load from cache
        id: cache
        uses: actions/cache/restore@v3
        with:
          path: |
            /usr/share/miniconda3
            ~/pycache
          # the below two settings mean we'll alway srestore the cache
          # but the cache hit output can tell us if we have to update afterwards
          key: min-${{ hashFiles('environment.yml')  }}
          restore-keys: |
            min

      - name: Fail on no cache restore
        if: steps.cache.outputs.cache-matched-key == ''
        run: |
          echo "Failed to restore any cache. exiting..."
          exit 1

      - name: Conda info
        run: |
          export PATH=/usr/share/miniconda3/bin:$PATH
          conda info
          conda list -n fiat_min

      - name: Verify the built dist/wheel is valid
        run: |
          export PATH=/usr/share/miniconda3/bin:$PATH
          source /usr/share/miniconda3/etc/profile.d/conda.sh
          conda activate fiat_min
          python -m pip install dist/delft_fiat*.whl
          fiat --help

  upload-to-test-pypi:
    needs: test-built-dist

    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/Delft-FIAT

    permissions:
      id-token: write

    steps:
      - name: Download the sdist and wheel
        uses: actions/download-artifact@v3
        with:
          name: releases
          path: dist/
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  upload-to-pypi:
    needs: test-built-dist
    if: ${{ github.event_name == 'release' && !github.event.act  }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: releases
          path: dist
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          verbose: true
