---
name: Code Analysis
on:
  push:
    branches:
      - master
    paths:
      - src/fiat/*
      - test/*
  pull_request:
    paths:
      - src/fiat/*
      - test/*
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    env:
      PYVERSION: "3.13"

    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
