---
name: Code analysis
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest" ] #, "macos-latest", "windows-latest"]
        python-version: ["3.11"] # fix tests to support older versions
        include:
          - os: ubuntu-latest
            label: linux-64

    name: SonarCloud
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate env yaml
        run: pip install tomli && python make_env.py test -p ${{ matrix.python-version }}.*

      - name: load from cache
        id: cache
        uses: actions/cache/restore@v3
        with:
          path: |
            /usr/share/miniconda3
            ~/pycache
          # the below two settings mean we'll alway srestore the cache
          # but the cache hit output can tell us if we have to update afterwards
          key: test-py${{ matrix.python-version }}-${{ hashFiles('environment.yml')  }}
          restore-keys: |
            test-py${{ matrix.python-version }}

      - name: Fail on no cache restore
        if: steps.cache.outputs.cache-matched-key == ''
        run: |
          echo "Failed to restore any cache. exiting..."
          exit 1

      - name: Update environment
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          export PATH=/usr/share/miniconda3/bin:$PATH
          mamba env update -n fiat_test -f environment.yml

      - name: Generate coverage report
        run: |
          export PATH=/usr/share/miniconda3/bin:$PATH
          mamba run -n fiat_test python -m pytest --verbose --cov=fiat --cov-report xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
