name: Test

on:
  push:
    branches: [ master ]
    paths:
      - test/*
      - src/fiat/*
      - .testdata/*
      - pyproject.toml
      - .github/workflows/test.yml
  pull_request:
    branches: [ master ]
    paths:
      - test/*
      - src/fiat/*
      - .testdata/*
      - pyproject.toml
      - .github/workflows/test.yml

jobs:
  Test:
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["311", "312", "313"]
        include:
          - os: ubuntu-latest
            label: linux-64

    name: ${{ matrix.label }} - py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.python-version }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Check-out source
        uses: actions/checkout@v4

      - name: Setup pixi env
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: "v0.40.3"
          environments: test-py${{ matrix.python-version }}
          locked: false
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'master' }}

      - name: Install fiat
        run: |
          pixi run -e test-py${{ matrix.python-version }} install-fiat

      - name: Create testdata
        run: |
          pixi run -e test-py${{ matrix.python-version }} generate-data

      - name: Test
        run: |
          pixi run -e test-py${{ matrix.python-version }} test-cov

      - name: Upload coverage to codecov.io
        if: matrix.python-version == '313'
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
