---
name: Test Package

on:
  push:
    branches: [ master ]
    paths:
      - test/*
      - src/fiat/*
      - .testdata/*
      - pyproject.toml
      - .github/workflows/test.yml
  pull_request:
    branches: [ master ]
    paths:
      - test/*
      - src/fiat/*
      - .testdata/*
      - pyproject.toml
      - .github/workflows/test.yml

jobs:
  test:
    defaults:
      run:
        shell: bash -l {0}
    env:
      branch_name: ${{ github.head_ref || github.ref_name }}
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["311", "312", "313"]
        include:
          - os: ubuntu-latest
            label: linux-64
          - os: windows-latest
            label: win-64

    name: ${{ matrix.label }} - py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.os }}-${{ matrix.python-version }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Check-out source
        uses: actions/checkout@v4

      - name: Setup pixi env
        uses: prefix-dev/setup-pixi@v0.8.12
        with:
          pixi-version: "v0.49.0"
          environments: test-py${{ matrix.python-version }}
          locked: false
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'master' }}

      - name: Create testdata
        run: |
          pixi run -e test-py${{ matrix.python-version }} generate-data

      - name: Test
        run: |
          pixi run -e test-py${{ matrix.python-version }} test-cov

      - name: Upload coverage to codecov.io
        if: matrix.python-version == '313'
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
